<a href="https://colab.research.google.com/github/khered20/UniManc_NADI2023_ArabicDialectToMSA_MT/blob/main/DataPreparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
import numpy as np

In [60]:
MSA_path = 'MADAR_Corpus/MADAR.corpus.MSA.tsv'
Cairo_path = 'MADAR_Corpus/MADAR.corpus.Cairo.tsv'
Tunis_path = 'MADAR_Corpus/MADAR.corpus.Tunis.tsv'
Doha_path = 'MADAR_Corpus/MADAR.corpus.Doha.tsv'
Beirut_path = 'MADAR_Corpus/MADAR.corpus.Beirut.tsv'
Rabat_path = 'MADAR_Corpus/MADAR.corpus.Rabat.tsv'
Jeddah_path = 'MADAR_Corpus/MADAR.corpus.Jeddah.tsv'
Riyadh_path = 'MADAR_Corpus/MADAR.corpus.Riyadh.tsv'
Muscat_path = 'MADAR_Corpus/MADAR.corpus.Muscat.tsv'
Alexandria_path = 'MADAR_Corpus/MADAR.corpus.Alexandria.tsv'
Aswan_path = 'MADAR_Corpus/MADAR.corpus.Aswan.tsv'
Jerusalem_path = 'MADAR_Corpus/MADAR.corpus.Jerusalem.tsv'
Amman_path = 'MADAR_Corpus/MADAR.corpus.Amman.tsv'
Salt_path = 'MADAR_Corpus/MADAR.corpus.Salt.tsv'
Damascus_path = 'MADAR_Corpus/MADAR.corpus.Damascus.tsv'
Aleppo_path = 'MADAR_Corpus/MADAR.corpus.Aleppo.tsv'
Algiers_path = 'MADAR_Corpus/MADAR.corpus.Algiers.tsv'
Fes_path = 'MADAR_Corpus/MADAR.corpus.Fes.tsv'
Sfax_path = 'MADAR_Corpus/MADAR.corpus.Sfax.tsv'
Tripoli_path = 'MADAR_Corpus/MADAR.corpus.Tripoli.tsv'
Benghazi_path = 'MADAR_Corpus/MADAR.corpus.Benghazi.tsv'
Mosul_path = 'MADAR_Corpus/MADAR.corpus.Mosul.tsv'
Khartoum_path = 'MADAR_Corpus/MADAR.corpus.Khartoum.tsv'
Baghdad_path = 'MADAR_Corpus/MADAR.corpus.Baghdad.tsv'
Sanaa_path = 'MADAR_Corpus/MADAR.corpus.Sanaa.tsv'
Basra_path = 'MADAR_Corpus/MADAR.corpus.Basra.tsv'

In [61]:
M_MSA = pd.read_csv(MSA_path, sep='\t')
M_Cairo = pd.read_csv(Cairo_path, sep='\t')  ## Egypt
M_Cairo['di_text']=M_Cairo['sent']
M_Cairo['data']='Madar'
M_Cairo['di_cty']='Cairo'
M_Cairo['di_cntry']='Egypt'
M_Cairo['di_reg']='Nile'
M_Cairo['MSA'] = M_MSA['sent']


M_Tunis = pd.read_csv(Tunis_path, sep='\t')  ## Tunis = Maghrebi
M_Tunis['di_text']=M_Tunis['sent']
M_Tunis['data']='Madar'
M_Tunis['di_cty']='Tunis'
M_Tunis['di_cntry']='Tunisia'
M_Tunis['di_reg']='Maghreb'
M_Tunis['MSA'] = M_MSA['sent']
df_combineA=pd.concat([M_Cairo,M_Tunis])

M_Beirut = pd.read_csv(Beirut_path, sep='\t') ## Lebanon = Levantine
M_Beirut['di_text']=M_Beirut['sent']
M_Beirut['data']='Madar'
M_Beirut['di_cty']='Beirut'
M_Beirut['di_cntry']='Lebanon'
M_Beirut['di_reg']='Levantine'
M_Beirut['MSA'] = M_MSA['sent']
df_combineA=pd.concat([df_combineA,M_Beirut])

M_Rabat = pd.read_csv(Rabat_path, sep='\t')  ## Morocco = Maghrebi
M_Rabat['di_text']=M_Rabat['sent']
M_Rabat['data']='Madar'
M_Rabat['di_cty']='Rabat'
M_Rabat['di_cntry']='Morocco'
M_Rabat['di_reg']='Maghreb'
M_Rabat['MSA'] = M_MSA['sent']
df_combineA=pd.concat([df_combineA,M_Rabat])

## Gulf
M_Doha = pd.read_csv(Doha_path, sep='\t')#['sent']  ## Qatar = Gulf
M_Doha['di_text']=M_Doha['sent']
M_Doha['data']='Madar'
M_Doha['di_cty']='Doha'
M_Doha['di_cntry']='Qatar'
M_Doha['di_reg']='Gulf'
M_Doha['MSA'] = M_MSA['sent']
df_combineA=pd.concat([df_combineA,M_Doha])

M_Jeddah = pd.read_csv(Jeddah_path, sep='\t')
M_Jeddah['di_text']=M_Jeddah['sent']
M_Jeddah['data']='Madar'
M_Jeddah['di_cty']='Jeddah'
M_Jeddah['di_cntry']='Saudi'
M_Jeddah['di_reg']='Gulf'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Jeddah['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Jeddah['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Jeddah])

M_Riyadh = pd.read_csv(Riyadh_path, sep='\t')
M_Riyadh['di_text']=M_Riyadh['sent']
M_Riyadh['data']='Madar'
M_Riyadh['di_cty']='Riyadh'
M_Riyadh['di_cntry']='Saudi'
M_Riyadh['di_reg']='Gulf'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Riyadh['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Riyadh['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Riyadh])

M_Muscat = pd.read_csv(Muscat_path, sep='\t')
M_Muscat['di_text']=M_Muscat['sent']
M_Muscat['data']='Madar'
M_Muscat['di_cty']='Muscat'
M_Muscat['di_cntry']='Oman'
M_Muscat['di_reg']='Gulf'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Muscat['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Muscat['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Muscat])


##################################################
##Egypt
M_Alexandria = pd.read_csv(Alexandria_path, sep='\t')
M_Alexandria['di_text']=M_Alexandria['sent']
M_Alexandria['data']='Madar'
M_Alexandria['di_cty']='Alexandria'
M_Alexandria['di_cntry']='Egypt'
M_Alexandria['di_reg']='Nile'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Alexandria['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Alexandria['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Alexandria])


#####
#####

M_Aswan = pd.read_csv(Aswan_path, sep='\t')
M_Aswan['di_text']=M_Aswan['sent']
M_Aswan['data']='Madar'
M_Aswan['di_cty']='Aswan'
M_Aswan['di_cntry']='Egypt'
M_Aswan['di_reg']='Nile'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Aswan['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Aswan['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Aswan])


## South Levantine
M_Jerusalem = pd.read_csv(Jerusalem_path, sep='\t')
M_Jerusalem['di_text']=M_Jerusalem['sent']
M_Jerusalem['data']='Madar'
M_Jerusalem['di_cty']='Jerusalem'
M_Jerusalem['di_cntry']='Palestine'
M_Jerusalem['di_reg']='Levantine'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Jerusalem['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Jerusalem['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Jerusalem])

M_Amman = pd.read_csv(Amman_path, sep='\t')
M_Amman['di_text']=M_Amman['sent']
M_Amman['data']='Madar'
M_Amman['di_cty']='Amman'
M_Amman['di_cntry']='Jordan'
M_Amman['di_reg']='Levantine'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Amman['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Amman['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Amman])

M_Salt = pd.read_csv(Salt_path, sep='\t')
M_Salt['di_text']=M_Salt['sent']
M_Salt['data']='Madar'
M_Salt['di_cty']='Salt'
M_Salt['di_cntry']='Jordan'
M_Salt['di_reg']='Levantine'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Salt['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Salt['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Salt])

## North Levantine
M_Damascus = pd.read_csv(Damascus_path, sep='\t')
M_Damascus['di_text']=M_Damascus['sent']
M_Damascus['data']='Madar'
M_Damascus['di_cty']='Damascus'
M_Damascus['di_cntry']='Syria'
M_Damascus['di_reg']='Levantine'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Damascus['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Damascus['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Damascus])

M_Aleppo = pd.read_csv(Aleppo_path, sep='\t')
M_Aleppo['di_text']=M_Aleppo['sent']
M_Aleppo['data']='Madar'
M_Aleppo['di_cty']='Aleppo'
M_Aleppo['di_cntry']='Syria'
M_Aleppo['di_reg']='Levantine'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Aleppo['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Aleppo['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Aleppo])


## Maghrebi
M_Algiers = pd.read_csv(Algiers_path, sep='\t')  ## Algeria
M_Algiers['di_text']=M_Algiers['sent']
M_Algiers['data']='Madar'
M_Algiers['di_cty']='Algiers'
M_Algiers['di_cntry']='Algeria'
M_Algiers['di_reg']='Maghreb'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Algiers['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Algiers['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Algiers])

M_Fes = pd.read_csv(Fes_path, sep='\t') ## Morocco
M_Fes['di_text']=M_Fes['sent']
M_Fes['data']='Madar'
M_Fes['di_cty']='Fes'
M_Fes['di_cntry']='Morocco'
M_Fes['di_reg']='Maghreb'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Fes['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Fes['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Fes])

M_Sfax = pd.read_csv(Sfax_path, sep='\t') ## Tunisia
M_Sfax['di_text']=M_Sfax['sent']
M_Sfax['data']='Madar'
M_Sfax['di_cty']='Sfax'
M_Sfax['di_cntry']='Tunisia'
M_Sfax['di_reg']='Maghreb'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Sfax['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Sfax['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Sfax])

M_Tripoli = pd.read_csv(Tripoli_path, sep='\t') ## Libya
M_Tripoli['di_text']=M_Tripoli['sent']
M_Tripoli['data']='Madar'
M_Tripoli['di_cty']='Tripoli'
M_Tripoli['di_cntry']='Libya'
M_Tripoli['di_reg']='Maghreb'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Tripoli['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Tripoli['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Tripoli])

M_Benghazi = pd.read_csv(Benghazi_path, sep='\t') ## Libya
M_Benghazi['di_text']=M_Benghazi['sent']
M_Benghazi['data']='Madar'
M_Benghazi['di_cty']='Benghazi'
M_Benghazi['di_cntry']='Libya'
M_Benghazi['di_reg']='Maghreb'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Benghazi['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Benghazi['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Benghazi])

M_Mosul = pd.read_csv(Mosul_path, sep='\t')
M_Mosul['di_text']=M_Mosul['sent']
M_Mosul['data']='Madar'
M_Mosul['di_cty']='Mosul'
M_Mosul['di_cntry']='Iraq'
M_Mosul['di_reg']='Mesopotamian'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Mosul['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Mosul['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Mosul])

M_Baghdad = pd.read_csv(Baghdad_path, sep='\t')
M_Baghdad['di_text']=M_Baghdad['sent']
M_Baghdad['data']='Madar'
M_Baghdad['di_cty']='Baghdad'
M_Baghdad['di_cntry']='Iraq'
M_Baghdad['di_reg']='Mesopotamian'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Baghdad['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Baghdad['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Baghdad])

M_Basra = pd.read_csv(Basra_path, sep='\t')
M_Basra['di_text']=M_Basra['sent']
M_Basra['data']='Madar'
M_Basra['di_cty']='Basra'
M_Basra['di_cntry']='Iraq'
M_Basra['di_reg']='Mesopotamian'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Basra['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Basra['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Basra])



M_Khartoum = pd.read_csv(Khartoum_path, sep='\t')
M_Khartoum['di_text']=M_Khartoum['sent']
M_Khartoum['data']='Madar'
M_Khartoum['di_cty']='Khartoum'
M_Khartoum['di_cntry']='Sudan'
M_Khartoum['di_reg']='Nile'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Khartoum['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Khartoum['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Khartoum])

M_Sanaa = pd.read_csv(Sanaa_path, sep='\t') ## Yemen
M_Sanaa['di_text']=M_Sanaa['sent']
M_Sanaa['data']='Madar'
M_Sanaa['di_cty']='Sanaa'
M_Sanaa['di_cntry']='Yemen'
M_Sanaa['di_reg']='Yemeni'
qq1=M_MSA[M_MSA['sentID.BTEC'].isin(M_Sanaa['sentID.BTEC'])]
qq1.reset_index(drop=True, inplace=True)
M_Sanaa['MSA'] = qq1['sent']
df_combineA=pd.concat([df_combineA,M_Sanaa])
print(len(df_combineA))

100000

The training dataset from MADAR

In [62]:

df_train6=df_combineA[df_combineA['split']=='corpus-6-train']
df_train26=df_combineA[df_combineA['split']=='corpus-6-test-corpus-26-train']

NADItrain=pd.concat([df_train6,df_train26])
print(len(NADItrain))

85000

For subtask 3, the datasets we found and used with MADAR training dataset:
<br>(1) PADIC
<br>(2) Dial2MSA
<br>(3) a semantic textual similarity (STS)
<br>(4) our own Emi-NADI dataset containing Emirati-to-MSA

<br>You can add the other datasets to MADAR training dataset, such as our translation of Emiraties NADI tweets.

In [63]:
uae2msa = pd.read_csv('uae2msa_fromNADItraining.csv')
uae2msa['di_text']=uae2msa['uae_tweet_cleaned']
uae2msa['data']='NADI'
uae2msa['di_cty']=''
uae2msa['di_cntry']='UAE'
uae2msa['di_reg']='Gulf'
uae2msa['MSA'] = uae2msa['msa_translation']

uae2msa[['uae_tweet_cleaned','translation_status','msa_translation']]

## For subtask 3 only
#df_combineA=pd.concat([df_combineA,uae2msa])

,uae_tweet_cleaned,translation_status,msa_translation
0,ولا علينا من حد ياخوي,verified,لا يهمنا من أحد يا أخي.
1,هه عيشي حياتج الخوف حلو تراه هه,verified,عَيِّشي حياتِكِ بِلا خَوفٍ، فَهو حلوٌ حقًا، صَ...
2,ما شاء الله وهذا هو ع قولتك غلط وضياع جي لعبك,verified,ما شاء الله، وهذا هو بناءً على قولك غير صحيح و...
3,مبروك لجمهور الشارجه الدوري تستاهلون الفرحه,verified,تهانينا لجمهور الشارجة بفوزهم بالدوري، أنتم تس...
4,ونعم وسبع انعام بيض الله ويهك يا ولد الصباح,verified,ونعم وسبعة أنعام بيض الله ويهنئك يا ولد الصباح.
...,...,...,...
2707,انت ممكن م تحط هالفيس,not verified,أنت لا تستطيع وضع هذا الفيسبوك.
2708,قلبي واعرفه زين مايفيد الرجا فيه لا حب حب ولا ...,not verified,قلبي وأعلمه جيدًا، لا يجدي الأمل فيه، لا يوجد ...
2709,موضه تسون عرسين الاول مع الاهل والثاني مكس,not verified,موضة تقومون بعقد اثنين من الأعراس، الأول مع ال...
2710,ما قدرت انام بس الحراره والزكام ولي يومين مادر...,not verified,لم أتمكن من النوم بسبب الحمى والزكام، ولم أدرس...
2711,لو انا وانتي غيمتان متجاورتان تلقي علي تحيه ال...,not verified,لو أنا وأنتِ غيمتان متجاورتان، تلقي عليَّ تحية...

In [64]:
NADItrain['1'] = NADItrain['MSA']
NADItrain['0'] = NADItrain['di_text']

From the training dataset, generate an additional pair where each of the source and target is the text written in MSA.

In [65]:
NADI_msa=NADItrain.copy()
NADI_msa['0'] = NADItrain['1']
NADI_msa=NADI_msa.drop_duplicates(['0','1'],keep= 'last')
len(NADI_msa)

10546

In [66]:
## Levantine dataset
NADItrain_lev=NADItrain[NADItrain['di_reg']=='Levantine']
print(len(NADItrain_lev))

18600

In [67]:
## Gulf dataset
NADItrain_glf=NADItrain[NADItrain['di_reg']=='Gulf']
NADItrain_lev['di_cty'].value_counts()
print(len(NADItrain_glf))

15400

In [68]:
## Egyption dataset
NADItrain_egy=NADItrain[NADItrain['di_cntry']=='Egypt']
NADItrain_egy['di_cty'].value_counts()
print(len(NADItrain_egy))

13800

In [69]:
## A joint dataset for the three regional dialects (Levantine, Gulf and Egyption).
NADIreg=pd.concat([NADItrain_lev,NADItrain_glf])
NADIreg=pd.concat([NADIreg,NADItrain_egy])
print(len(NADIreg))

47800

Add the generated MSA pairs to each dataset, delete duplicates, shuffle samples and save the datasets for both individual and regional dialects datasets

In [70]:
NADItrain_lev_msa=pd.concat([NADItrain_lev,NADI_msa])
NADItrain_glf_msa=pd.concat([NADItrain_glf,NADI_msa])
NADItrain_egy_msa=pd.concat([NADItrain_egy,NADI_msa])

NADItrain_lev_msa=NADItrain_lev_msa.drop_duplicates(['0','1'],keep= 'last')
NADItrain_glf_msa=NADItrain_glf_msa.drop_duplicates(['0','1'],keep= 'last')
NADItrain_egy_msa=NADItrain_egy_msa.drop_duplicates(['0','1'],keep= 'last')

NADItrain_lev_msa[['0','1']].sample(frac=1).to_csv('levMADARmsa.csv', index=False)
NADItrain_glf_msa[['0','1']].sample(frac=1).to_csv('glfMADARmsa.csv', index=False)
NADItrain_egy_msa[['0','1']].sample(frac=1).to_csv('egyMADARmsa.csv', index=False)


NADIreg_msa=pd.concat([NADIreg,NADI_msa])
NADIreg_msa=NADIreg_msa.drop_duplicates(['0','1'],keep= 'last')
NADIreg_msa[['0','1']].sample(frac=1).to_csv('regMADARmsa.csv', index=False)